-- 1141
-- https://leetcode.com/problems/user-activity-for-the-past-30-days-i/

SELECT ACTIVITY_DATE AS DAY, COUNT(DISTINCT(USER_ID)) 
AS ACTIVE_USERS FROM ACTIVITY WHERE ACTIVITY_DATE <= "2019-07-27"
AND ACTIVITY_DATE > DATE_SUB("2019-07-27", INTERVAL 30 DAY)
GROUP BY ACTIVITY_DATE;