-- 1484
-- https://leetcode.com/problems/group-sold-products-by-the-date/

SELECT SELL_DATE, COUNT(DISTINCT(PRODUCT)) AS NUM_SOLD,
GROUP_CONCAT(DISTINCT(PRODUCT)) AS PRODUCTS
FROM ACTIVITIES GROUP BY SELL_DATE ORDER BY SELL_DATE