-- 1587
-- https://leetcode.com/problems/bank-account-summary-ii/

SELECT U.NAME, SUM(T.AMOUNT) AS BALANCE
FROM TRANSACTIONS AS T LEFT JOIN USERS AS U
ON T.ACCOUNT = U.ACCOUNT GROUP BY T.ACCOUNT
HAVING BALANCE > 10000;