-- 1693
-- https://leetcode.com/problems/daily-leads-and-partners/

SELECT DATE_ID, MAKE_NAME, COUNT(DISTINCT(LEAD_ID)) AS 
UNIQUE_LEADS, COUNT(DISTINCT(PARTNER_ID)) AS UNIQUE_PARTNERS
FROM DAILYSALES GROUP BY MAKE_NAME, DATE_ID;