-- 175
-- https://leetcode.com/problems/combine-two-tables/

SELECT EMPLOYEE_ID FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN 
(SELECT EMPLOYEE_ID FROM SALARIES) 
UNION
SELECT EMPLOYEE_ID FROM SALARIES
WHERE EMPLOYEE_ID NOT IN 
(SELECT EMPLOYEE_ID FROM EMPLOYEES)
ORDER BY EMPLOYEE_ID;